info:
  name: list Zaaktype Bpmn Configurations
  type: http
  seq: 2

http:
  method: GET
  url: "{{baseUrl}}/rest/zaaktype-bpmn-configuration"
  headers:
    - name: Accept
      value: application/json
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: OK
    request:
      url: "{{baseUrl}}/rest/zaaktype-bpmn-configuration"
      method: GET
      headers:
        - name: Accept
          value: application/json
    response:
      statusText: "200"
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          [
            {
              "zaaktypeUuid": "fbBfcfdA-DBf8-b680-8C6B-d6BF1B95DcAB",
              "zaaktypeOmschrijving": "f",
              "bpmnProcessDefinitionKey": "string",
              "groepNaam": "U",
              "zaakbeeindigParameters": [
                {
                  "id": null,
                  "zaakbeeindigReden": {
                    "id": "string",
                    "naam": "string"
                  },
                  "resultaattype": {
                    "id": "83D7a6A4-5625-2F17-dFce-Fd6D2BCE1CDf",
                    "naam": null,
                    "naamGeneriek": "string",
                    "vervaldatumBesluitVerplicht": true,
                    "datumKenmerkVerplicht": false,
                    "besluitVerplicht": true,
                    "toelichting": "string",
                    "archiefNominatie": "string",
                    "archiefTermijn": "string",
                    "selectielijst": "string",
                    "bronArchiefprocedure": {
                      "afleidingswijze": "TERMIJN",
                      "datumkenmerk": "string",
                      "einddatumBekend": true,
                      "objecttype": "INRICHTINGSELEMENT",
                      "registratie": "string",
                      "procestermijn": "string"
                    }
                  }
                },
                {
                  "id": 2111,
                  "zaakbeeindigReden": {
                    "id": "string",
                    "naam": "string"
                  },
                  "resultaattype": {
                    "id": "4ccC1e4F-2A37-EC4f-ea24-4de66946FE39",
                    "naam": "string",
                    "naamGeneriek": null,
                    "vervaldatumBesluitVerplicht": true,
                    "datumKenmerkVerplicht": true,
                    "besluitVerplicht": true,
                    "toelichting": null,
                    "archiefNominatie": "string",
                    "archiefTermijn": "string",
                    "selectielijst": null,
                    "bronArchiefprocedure": {
                      "afleidingswijze": "TERMIJN",
                      "datumkenmerk": "string",
                      "einddatumBekend": true,
                      "objecttype": "ZAKELIJK_RECHT",
                      "registratie": "string",
                      "procestermijn": "string"
                    }
                  }
                }
              ],
              "id": null,
              "productaanvraagtype": "string",
              "creatiedatum": "1959-04-02T16:53:48.923Z",
              "defaultBehandelaarId": null,
              "betrokkeneKoppelingen": {
                "id": null,
                "zaakafhandelParameters": {
                  "value": "<Circular reference to #/components/schemas/RestZaakafhandelParameters detected>"
                },
                "brpKoppelen": true,
                "kvkKoppelen": false
              },
              "brpDoelbindingen": {
                "id": 7514,
                "zaakafhandelParameters": {
                  "value": "<Circular reference to #/components/schemas/RestZaakafhandelParameters detected>"
                },
                "zoekWaarde": "string",
                "raadpleegWaarde": null,
                "verwerkingregisterWaarde": null
              },
              "zaakNietOntvankelijkResultaattype": {
                "id": "D4cbb6ff-f5C0-904a-89FF-07D6deE69d99",
                "naam": "string",
                "naamGeneriek": null,
                "vervaldatumBesluitVerplicht": false,
                "datumKenmerkVerplicht": false,
                "besluitVerplicht": false,
                "toelichting": null,
                "archiefNominatie": "string",
                "archiefTermijn": null,
                "selectielijst": null,
                "bronArchiefprocedure": {
                  "afleidingswijze": "TERMIJN",
                  "datumkenmerk": "string",
                  "einddatumBekend": false,
                  "objecttype": "WOZ_DEELOBJECT",
                  "registratie": "string",
                  "procestermijn": "string"
                }
              }
            },
            {
              "zaaktypeUuid": "8bBaa7D7-a0AA-C644-A36E-D3F748c8DA2d",
              "zaaktypeOmschrijving": "s",
              "bpmnProcessDefinitionKey": "string",
              "groepNaam": "/",
              "zaakbeeindigParameters": [
                {
                  "id": 1200,
                  "zaakbeeindigReden": {
                    "id": "string",
                    "naam": "string"
                  },
                  "resultaattype": {
                    "id": "BE6BDaeD-2aD3-95D2-C61A-aB8C8cA7bB0E",
                    "naam": "string",
                    "naamGeneriek": null,
                    "vervaldatumBesluitVerplicht": true,
                    "datumKenmerkVerplicht": true,
                    "besluitVerplicht": true,
                    "toelichting": null,
                    "archiefNominatie": null,
                    "archiefTermijn": null,
                    "selectielijst": null,
                    "bronArchiefprocedure": {
                      "afleidingswijze": "HOOFDZAAK",
                      "datumkenmerk": "string",
                      "einddatumBekend": true,
                      "objecttype": "NIET_NATUURLIJK_PERSOON",
                      "registratie": "string",
                      "procestermijn": "string"
                    }
                  }
                },
                {
                  "id": null,
                  "zaakbeeindigReden": {
                    "id": "string",
                    "naam": "string"
                  },
                  "resultaattype": {
                    "id": "D9a35cDE-B0d3-1F3C-c8Dc-B8bd5faCA33e",
                    "naam": null,
                    "naamGeneriek": "string",
                    "vervaldatumBesluitVerplicht": true,
                    "datumKenmerkVerplicht": false,
                    "besluitVerplicht": true,
                    "toelichting": null,
                    "archiefNominatie": "string",
                    "archiefTermijn": "string",
                    "selectielijst": null,
                    "bronArchiefprocedure": {
                      "afleidingswijze": "HOOFDZAAK",
                      "datumkenmerk": "string",
                      "einddatumBekend": false,
                      "objecttype": "OVERIGE",
                      "registratie": "string",
                      "procestermijn": "string"
                    }
                  }
                }
              ],
              "id": 2066,
              "productaanvraagtype": "string",
              "creatiedatum": "1954-11-16T03:12:06.095Z",
              "defaultBehandelaarId": null,
              "betrokkeneKoppelingen": {
                "id": 1716,
                "zaakafhandelParameters": {
                  "value": "<Circular reference to #/components/schemas/RestZaakafhandelParameters detected>"
                },
                "brpKoppelen": false,
                "kvkKoppelen": false
              },
              "brpDoelbindingen": {
                "id": null,
                "zaakafhandelParameters": {
                  "value": "<Circular reference to #/components/schemas/RestZaakafhandelParameters detected>"
                },
                "zoekWaarde": "string",
                "raadpleegWaarde": "string",
                "verwerkingregisterWaarde": null
              },
              "zaakNietOntvankelijkResultaattype": {
                "id": "AD49A15B-f5Ec-62B5-7024-F55D97EDF773",
                "naam": "string",
                "naamGeneriek": null,
                "vervaldatumBesluitVerplicht": true,
                "datumKenmerkVerplicht": false,
                "besluitVerplicht": false,
                "toelichting": null,
                "archiefNominatie": "string",
                "archiefTermijn": "string",
                "selectielijst": null,
                "bronArchiefprocedure": {
                  "afleidingswijze": "AFGEHANDELD",
                  "datumkenmerk": "string",
                  "einddatumBekend": true,
                  "objecttype": "ZAKELIJK_RECHT",
                  "registratie": "string",
                  "procestermijn": "string"
                }
              }
            }
          ]
