services:
  keycloak:
    user: "${UID}:${GID}"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  keycloak-database:
    user: "${UID}:${GID}"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  zac-database:
    user: "${UID}:${GID}"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  openzaak-database:
    user: "${UID}:${GID}"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  openzaak.local:
    user: "${UID}:${GID}"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # This container name must contain a '.' or else Open Zaak will respond with a 400
  # error on certain API requests caused by an internal 'invalid URL' error.
  objecten-api.local:
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  objecten-api-database:
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  objecten-api-import:
    user: "${UID}:${GID}"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  objecttypen-api:
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  objecttypen-api-database:
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  objecttypen-api-import:
    user: "${UID}:${GID}"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  solr:
    user: "${UID}:${GID}"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Create the 'zac' core and start solr
    command: solr-precreate zac

  opa:
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  openldap:
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  brp-personen-mock:
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  openklant-database:
    user: "${UID}:${GID}"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  openklant.local:
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  smartdocuments-wiremock:
    user: "${UID}:${GID}"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  kvk-wiremock:
    user: "${UID}:${GID}"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  opa-tests:
    user: "1000:1000"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  office-converter:
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  otel-collector:
    user: "${UID}:${GID}"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  tempo:
    user: "${UID}:${GID}"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  prometheus:
    user: "${UID}:${GID}"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    user: "${UID}:${GID}"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  zac:
    user: "${UID}:${GID}"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"
