info:
  name: get Zaaktype Bpmn Configuration
  type: http
  seq: 1

http:
  method: GET
  url: "{{baseUrl}}/rest/zaaktype-bpmn-configuration/:processDefinitionKey"
  headers:
    - name: Accept
      value: application/json
  params:
    - name: processDefinitionKey
      value: string
      type: path
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: OK
    request:
      url: "{{baseUrl}}/rest/zaaktype-bpmn-configuration/:processDefinitionKey"
      method: GET
      headers:
        - name: Accept
          value: application/json
      params:
        - name: processDefinitionKey
          value: string
          type: path
    response:
      statusText: "200"
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "zaaktypeUuid": "4Aa6ed4e-5A96-b05a-3afb-c8d12A7470aA",
            "zaaktypeOmschrijving": "x",
            "bpmnProcessDefinitionKey": "string",
            "groepNaam": "'",
            "zaakbeeindigParameters": [
              {
                "id": null,
                "zaakbeeindigReden": {
                  "id": "string",
                  "naam": "string"
                },
                "resultaattype": {
                  "id": "A09C592a-bFcB-B0Ea-eEF8-e1F3f01de051",
                  "naam": "string",
                  "naamGeneriek": null,
                  "vervaldatumBesluitVerplicht": false,
                  "datumKenmerkVerplicht": false,
                  "besluitVerplicht": false,
                  "toelichting": "string",
                  "archiefNominatie": "string",
                  "archiefTermijn": "string",
                  "selectielijst": null,
                  "bronArchiefprocedure": {
                    "afleidingswijze": "VERVALDATUM_BESLUIT",
                    "datumkenmerk": "string",
                    "einddatumBekend": true,
                    "objecttype": "WEGDEEL",
                    "registratie": "string",
                    "procestermijn": "string"
                  }
                }
              },
              {
                "id": 3307,
                "zaakbeeindigReden": {
                  "id": "string",
                  "naam": "string"
                },
                "resultaattype": {
                  "id": "496D7201-9837-0cF7-EA63-3624E5Ec682B",
                  "naam": "string",
                  "naamGeneriek": "string",
                  "vervaldatumBesluitVerplicht": false,
                  "datumKenmerkVerplicht": true,
                  "besluitVerplicht": false,
                  "toelichting": "string",
                  "archiefNominatie": "string",
                  "archiefTermijn": null,
                  "selectielijst": "string",
                  "bronArchiefprocedure": {
                    "afleidingswijze": "ANDER_DATUMKENMERK",
                    "datumkenmerk": "string",
                    "einddatumBekend": true,
                    "objecttype": "OVERIGE",
                    "registratie": "string",
                    "procestermijn": "string"
                  }
                }
              }
            ],
            "id": null,
            "productaanvraagtype": "string",
            "creatiedatum": "1994-11-19T19:30:16.420Z",
            "defaultBehandelaarId": null,
            "betrokkeneKoppelingen": {
              "id": 1797,
              "zaakafhandelParameters": {
                "value": "<Circular reference to #/components/schemas/RestZaakafhandelParameters detected>"
              },
              "brpKoppelen": false,
              "kvkKoppelen": true
            },
            "brpDoelbindingen": {
              "id": 6309,
              "zaakafhandelParameters": {
                "value": "<Circular reference to #/components/schemas/RestZaakafhandelParameters detected>"
              },
              "zoekWaarde": null,
              "raadpleegWaarde": null,
              "verwerkingregisterWaarde": null
            },
            "zaakNietOntvankelijkResultaattype": {
              "id": "84c6b560-7CE2-0c59-E804-1aAcFd0dB894",
              "naam": "string",
              "naamGeneriek": "string",
              "vervaldatumBesluitVerplicht": false,
              "datumKenmerkVerplicht": true,
              "besluitVerplicht": false,
              "toelichting": null,
              "archiefNominatie": "string",
              "archiefTermijn": "string",
              "selectielijst": "string",
              "bronArchiefprocedure": {
                "afleidingswijze": "HOOFDZAAK",
                "datumkenmerk": "string",
                "einddatumBekend": true,
                "objecttype": "ENKELVOUDIG_DOCUMENT",
                "registratie": "string",
                "procestermijn": "string"
              }
            }
          }
