#
# SPDX-FileCopyrightText: 2024 INFO.nl
# SPDX-License-Identifier: EUPL-1.2+
#
name: Check SPDX License Headers

on:
  pull_request:
  merge_group:
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

# Only allow a single concurrent run per branch. Cancel in-progress runs on multiple pushes when not on main branch.  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'main')}}

jobs:
  check-spdx-license-headers:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

    - name: Check License Header
      uses: apache/skywalking-eyes/header@61275cc80d0798a405cb070f7d3a8aaf7cf2c2c1 # v0.8.0
      with:
        log: info
        config: .licenserc.yaml
        token: ${{ github.token }}
        mode: check
