#
# SPDX-FileCopyrightText: 2023 INFO.nl
# SPDX-License-Identifier: EUPL-1.2+
#
name: Cleanup cache after PR close

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  actions: write

jobs:
  cleanup-branch-cache:
    runs-on: ubuntu-24.04
    steps:
      - uses: Friedinger/DeleteBranchCaches@f42f72afd01dde24a516ac9f82aaed9e2b319ed7 # v2.4.1
        with:
          github-token: ${{ github.token }}
          # Specify explicitly because the ref at the time of merging will be a branch name such as 'main', 'develop'
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
