#
# SPDX-FileCopyrightText: 2023 Lifely
# SPDX-License-Identifier: EUPL-1.2+
#
name: Cleanup cache after PR close

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  cleanup-branch-cache:
    runs-on: ubuntu-24.04
    steps:
      - uses: snnaplab/delete-branch-cache-action@20f7992a7b8b51aa719420d11b32c9d34a5eb362 # v1.0.0
        with:
          # Specify explicitly because the ref at the time of merging will be a branch name such as 'main', 'develop'
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
